Fix problems with cachePath service option
webdriverio-community/wdio-vscode-service pull request #107
Opened 2024-02-16 15:59 UTC by ilia-db

Using the `vscode` service with the `cachePath` option:
```js
services: [["vscode", {cachePath: "/tmp/wdio-vscode-service"}]],
```

On the `6.0.0` version this results failure to run tests with this error:
```
ERROR @wdio/runner: Error: Invalid or unsupported WebDriver capabilities found ("cachePath"). Ensure to only use valid W3C WebDriver capabilities (see https://w3c.github.io/webdriver/#capabilities).If you run your tests on a remote vendor, like Sauce Labs or BrowserStack, make sure that you put them into vendor specific capabilities, e.g. "sauce:options" or "bstack:options". Please reach out to your vendor support team if you have further questions.
```

`cachePath` is indeed not a capability based on any of the wdio or webdriver types.

Looking at the old `5.*` code, assigning `options` to the capabilities made sense because `options` field actually contained [different things in the `wdio-chromedriver-service/launcher` base class](https://github.com/webdriverio-community/wdio-chromedriver-service/blob/104e63525faa156866aa521397ae56ffc6059a8f/src/launcher.ts#L47).

Right now the options are only relevant for the `vscode` service, so I've removed all logic that merges them into capabilities.

2024-02-16 17:25 UTC, christian-bromann requested changes

2024-02-16 17:25 UTC, christian-bromann commented on src/launcher.ts
> -    fileExist, directoryExists, isMultiremote, isChrome
We should remove `isMultiremote` and `isChrome` entirely then, since these functions aren't used anymore.

2024-02-19 16:06 UTC, seanpoulter commented
The build fails for the same reason as https://github.com/webdriverio/webdriverio/pull/12305. I'll open a PR to bump those dependencies when the workflows pass.

2024-02-20 14:51 UTC, seanpoulter approved these changes

2024-02-20 15:32 UTC, christian-bromann approved these changes

2024-02-20 15:32 UTC, merged